name: issue closed
on:
  issues:
    types: [closed]

jobs:
  capture_closing_message:
    runs-on: ubuntu-latest
    name: Capture closing message
    steps:
      - name: Get issue details
        id: issue_details
        uses: actions/github-script@v3
        with:
          script: |-
            echo ${{ github.event.issue }}


