name: Issue Closed Pipeline

on:
  issues:
    types:
      - closed
    branches:
      - main

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          if ${{ github.event.issue.body }} == yes; then
            echo ${{ github.event.issue.body }}
            echo ${{ toJSON(github.event.issue.assignees) }}
          else
            echo ${{ toJSON(github.event.issue.assignees) }}
            echo "erro"
            echo ${{ github.event.issue.body }}
          fi
