name: issue closed
on:
  issues:
    types: [closed]

jobs:
  capture_closing_message:
    runs-on: ubuntu-latest
    name: Capture closing message
    steps:
      - name: Get issue details
        id: issue_details
        uses: actions/github-script@v3
        with:
          script: |-
          
            const issue = github.issues.get({issue_number: context.issue.number});
            const text = issue.data.body;
            const author = issue.data.user.login;
      - name: Output the message
        run: |- 
            echo "The message was sent by ${{ steps.issue_details.outputs.author }} and it said ${{ steps.issue_details.outputs.text }}"
