name: issue closed
on:
  issues:
    types: [closed]

jobs:
  capture_closing_message:
    runs-on: ubuntu-latest
    name: Capture closing message
    steps:
      - name: Get issue details
        id: issue_details
        run: |-
          echo $(curl -H 'Authorization: token ${{ env.GITHUB_TOKEN }}' 'https://api.github.com/repos/issue/issues/${{ github.event.issue.number }}')


