name: Build and push Docker image

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write 
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ss
        run: |-
          echo ${{ toJSON(github) }}
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: ${{ github }}
          body: ${{ github.sha }}
          assignees: ARCamacho,victorsantosV
